version: '2.1'
orbs:
  welcome: circleci/welcome-orb@0.4.1
parameters:
  test1:
    description: test1
    type: boolean
    default: false
  test2:
    description: test2
    type: boolean
    default: false
workflows:
  welcome1:
    when:
      equal: [ true, << pipeline.parameters.test1 >> ]
    jobs:
      - test1
  welcome2:
    when:
      and:
        - equal: [ true, << pipeline.parameters.test2 >> ]
        - matches:
            pattern: "^.*pull.*$"
            value: "${CI_PULL_REQUEST}"
    jobs:
      - test2

jobs:
  test1:
    docker:
     - image: alpine
    steps:
      - run:
          name: test1
          command: echo "test1"
  test2:
    docker:
     - image: alpine
    steps:
      - run:
          name: test2
          command: echo "test2 ${CI_PULL_REQUEST}"
