version: '2.1'
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
  welcome2:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
